# Generated by Django 5.1 on 2024-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('definition', models.TextField()),
                ('image', models.ImageField(default='/media/product_images/default.png', upload_to='product_image')),
            ],
        ),
    ]
